### ISSUE TITLE
Widget bug

### ISSUE THREAD

**Issue by crisla** [davidrpugh/pyAM#12]
Something inside the code for the widget seems to make it deliver weird results, like getting the identity function for cases when omega_a and omega_b are different.

**Comment by davidrpugh** [comment]
@crisla 

Unfortunately this appears to be a deeper problem.  I am able to get the identity function for `omega_A = omega_B = 0.5` and `0.25 = omega_B = 1 - 0.75 = omega_A` and `0.25 = omega_A = 1 - 0.75 = omega_B` outside of the widget.  Not obvious to me what is causing this problem.  I don't recall see it in earlier versions.

**Comment by davidrpugh** [comment]
@crisla 

Sorted it! Code `B = l**omega_B * r**(1 - omega_B)` and then set `F=F` when constructing the `problem` instance in the workbook.  Issue goes away!  Appears that taking the limit somehow introduced a bug...not sure why.

Does this make sense? Does this fix the issue for you?

**Comment by crisla** [comment]
It did fixed the issue! I found weird stuff by looking at the limit, but after talking yesterday I thought it was just the unsimplified nature of sympy. Thanks!
